version: '3.7'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=integrator!23
    ports:
      - 1433:1433
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=integrator
      - MYSQL_PASSWORD=integrator!23
      - MYSQL_DATABASE=Integrator
    ports:
      - 3306:3306
