version: '3.7'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=integrator!23
    ports:
      - 1433:1433
  mysql:
    image: bitnami/mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: integrator!23
      MYSQL_USER: integrator
      MYSQL_PASSWORD: integrator
      MYSQL_DATABASE: integrator
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    ports:
      - 3306:3306
  pg:
    image: postgres:15.2
    environment:
      POSTGRES_USER: integrator
      POSTGRES_DB: integrator
      POSTGRES_PASSWORD: integrator!23
    ports:
      - 5432:5432
