version: 2
jobs:
  build:
    docker:
      - image: node:10

      - image: mcr.microsoft.com/mssql/server
        environment:
          ACCEPT_EULA: Y
          SA_PASSWORD: integrator!23
      - image: mysql:5.7
        environment:
          MYSQL_RANDOM_ROOT_PASSWORD: yes
          MYSQL_USER: integrator
          MYSQL_PASSWORD: integrator!23
          MYSQL_DATABASE: Integrator
      - image: postgres
        environment:
          POSTGRES_USER: integrator
          POSTGRES_DB: Integrator

    working_directory: ~/repo

